# Generated by Django 3.1.4 on 2021-01-26 07:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='نمایش عمومی؟')),
                ('is_valid', models.BooleanField(default=False, verbose_name='تایید شده؟')),
                ('pub_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('val_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تایید')),
                ('img_path', models.FileField(upload_to='', verbose_name='محل ذخیره تصویر')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان مقاله')),
                ('text', models.TextField(verbose_name='متن مقاله')),
            ],
        ),
        migrations.CreateModel(
            name='BlogUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره تلفن')),
                ('img_path', models.FileField(upload_to='', verbose_name='محل ذخیره عکس')),
                ('is_auther', models.BooleanField(default=False, verbose_name='نویسنده است؟')),
                ('is_editor', models.BooleanField(default=False, verbose_name='ویراستار است؟')),
                ('is_manager', models.BooleanField(default=False, verbose_name='مدیر است؟')),
                ('is_deactive', models.BooleanField(default=False, verbose_name='غیر فعال شده؟')),
                ('bio', models.CharField(max_length=250, verbose_name='درباره من')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن نظر')),
                ('is_valid', models.BooleanField(default=False, verbose_name='تایید شده؟')),
                ('pub_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('val_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تایید')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article', verbose_name='مقاله')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='برچسب')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='دسته بندی')),
                ('super_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.topic', verbose_name='فرا مجموعه')),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='blog.bloguser', verbose_name='نویسنده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followings', to='blog.bloguser', verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField(default=True, verbose_name='پسند؟')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.comment', verbose_name='نظر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.bloguser', verbose_name='کاربر')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='like',
            field=models.ManyToManyField(related_name='Clikes', through='blog.CommentLike', to='blog.BlogUser', verbose_name='پسند'),
        ),
        migrations.AddField(
            model_name='comment',
            name='response_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='response', to='blog.comment', verbose_name='پاسخ به'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.bloguser', verbose_name='نویسنده'),
        ),
        migrations.AddField(
            model_name='comment',
            name='validator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cvalidated', to='blog.bloguser', verbose_name='تایید کننده'),
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarkers', to='blog.article', verbose_name='مقاله')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='blog.bloguser', verbose_name='کاربر')),
            ],
        ),
        migrations.AddField(
            model_name='bloguser',
            name='bookmark',
            field=models.ManyToManyField(related_name='bookmarkedBy', through='blog.Bookmark', to='blog.Article', verbose_name='نشان کردن'),
        ),
        migrations.AddField(
            model_name='bloguser',
            name='follow',
            field=models.ManyToManyField(related_name='followedBy', through='blog.Follow', to='blog.BlogUser', verbose_name='دنبال کردن'),
        ),
        migrations.CreateModel(
            name='ArticleLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField(default=True, verbose_name='پسند؟')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article', verbose_name='مقاله')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.bloguser', verbose_name='کاربر')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='auther',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published', to='blog.bloguser', verbose_name='نویسنده'),
        ),
        migrations.AddField(
            model_name='article',
            name='like',
            field=models.ManyToManyField(related_name='Alikes', through='blog.ArticleLike', to='blog.BlogUser', verbose_name='پسند'),
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(blank=True, to='blog.Tag', verbose_name='برچسب'),
        ),
        migrations.AddField(
            model_name='article',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.topic', verbose_name='دسته بندی'),
        ),
        migrations.AddField(
            model_name='article',
            name='validator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Avalidated', to='blog.bloguser', verbose_name='تایید کننده'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('auther', 'user'), name='follow'),
        ),
        migrations.AddConstraint(
            model_name='commentlike',
            constraint=models.UniqueConstraint(fields=('comment', 'user'), name='comment_like'),
        ),
        migrations.AddConstraint(
            model_name='bookmark',
            constraint=models.UniqueConstraint(fields=('article', 'user'), name='bookmark'),
        ),
        migrations.AddConstraint(
            model_name='articlelike',
            constraint=models.UniqueConstraint(fields=('article', 'user'), name='article_like'),
        ),
    ]
