# Generated by Django 3.1.4 on 2021-01-26 13:51

import blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img_path',
            field=models.FileField(upload_to='%Y/%m/%d/', verbose_name='محل ذخیره تصویر'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نمایش عمومی؟'),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='img_path',
            field=models.FileField(upload_to=blog.models.BlogUser.user_directory_path, verbose_name='محل ذخیره عکس'),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='نام کاربری'),
        ),
    ]
