# Generated by Django 3.1.4 on 2021-02-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210131_1749'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='follow',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='auther',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='bloguser',
            old_name='is_auther',
            new_name='is_author',
        ),
        migrations.RenameField(
            model_name='bloguser',
            old_name='is_deactive',
            new_name='is_inactive',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='auther',
            new_name='author',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('author', 'user'), name='follow'),
        ),
    ]
