# Generated by Django 3.0.5 on 2021-02-08 05:57

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210203_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloguser',
            old_name='bookmark',
            new_name='bookmarked_articles',
        ),
        migrations.RenameField(
            model_name='bloguser',
            old_name='follow',
            new_name='followers',
        ),
        migrations.RemoveField(
            model_name='article',
            name='like',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='like',
        ),
        migrations.AddField(
            model_name='article',
            name='user_liked',
            field=models.ManyToManyField(related_name='alikes', through='blog.ArticleLike', to='blog.BlogUser', verbose_name='پسند'),
        ),
        migrations.AddField(
            model_name='comment',
            name='uesr_liked',
            field=models.ManyToManyField(related_name='clikes', through='blog.CommentLike', to='blog.BlogUser', verbose_name='پسند'),
        ),
        migrations.AlterField(
            model_name='article',
            name='img_path',
            field=models.ImageField(upload_to='%Y/%m/%d/', verbose_name='محل ذخیره تصویر'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(auto_now_add=True, verbose_name='تاریخ انتشار'),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='img_path',
            field=models.ImageField(upload_to=blog.models.BlogUser.user_directory_path, verbose_name='محل ذخیره عکس'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateField(auto_now_add=True, verbose_name='تاریخ انتشار'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='blog.BlogUser', verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='blog.BlogUser', verbose_name='کاربر'),
        ),
    ]
