# Generated by Django 3.0.5 on 2021-02-28 09:17

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210226_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleVector',
            fields=[
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='blog.Article')),
                ('embedding', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=100)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='is_vectorized',
            field=models.BooleanField(default=False),
        ),
    ]
