# Generated by Django 3.0.5 on 2021-03-01 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210228_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogUserCrawled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TagCrawled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, unique=True, verbose_name='برچسب')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleCrawled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_path', models.URLField(max_length=750, null=True)),
                ('title', models.CharField(max_length=350, verbose_name='عنوان مقاله')),
                ('text', models.TextField(verbose_name='متن مقاله')),
                ('likes', models.IntegerField()),
                ('comments', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.BlogUserCrawled', verbose_name='نویسنده')),
                ('tag', models.ManyToManyField(blank=True, to='blog.TagCrawled', verbose_name='برچسب')),
            ],
        ),
    ]
