# Generated by Django 3.0.5 on 2021-03-01 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_articlecrawled_blogusercrawled_tagcrawled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img_path',
            field=models.ImageField(max_length=750, upload_to='%Y/%m/%d/', verbose_name='محل ذخیره تصویر'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=350, verbose_name='عنوان مقاله'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=55, unique=True, verbose_name='برچسب'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=55, verbose_name='دسته بندی'),
        ),
    ]
