# Generated by Django 3.0.5 on 2021-03-01 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210301_2309'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleCrawled',
        ),
        migrations.DeleteModel(
            name='BlogUserCrawled',
        ),
        migrations.DeleteModel(
            name='TagCrawled',
        ),
    ]
